local build = require("lib.build")

describe("lib.build.empty_bin_error", function()
    local msg = build.empty_bin_error("/tmp/install/bin")

    it("includes the offending path", function()
        assert.is_truthy(msg:find("/tmp/install/bin", 1, true))
    end)

    it("mentions bin_path as a remediation", function()
        assert.is_truthy(msg:find("bin_path", 1, true))
    end)

    it("mentions installArtifact as a remediation", function()
        assert.is_truthy(msg:find("installArtifact", 1, true))
    end)
    describe("fallback_zig_failure_hint", function()
        it("mentions why active zig was used", function()
            local msg = build.fallback_zig_failure_hint("0.16.0")
            assert.is_truthy(msg:find("did not declare minimum_zig_version", 1, true))
            assert.is_truthy(msg:find("no zig_version opt was set", 1, true))
            assert.is_truthy(msg:find("active Zig 0.16.0", 1, true))
        end)

        it("suggests both user and upstream remediations", function()
            local msg = build.fallback_zig_failure_hint("0.16.0")
            assert.is_truthy(msg:find("set zig_version", 1, true))
            assert.is_truthy(msg:find("add minimum_zig_version", 1, true))
        end)
    end)
end)
